### PR TITLE
change of url in readme

### PR DESCRIPTION
**Pull request by markozxuu**
## Main changes 👁 

- the readme file was modified :)

https://react-notify-azjjh2kkw.now.sh/ to https://react-notify.now.sh

### CODE REVIEW

**Review by Developerayo — APPROVED** [review]
Good eye @MAPESO thanks.

**Comment by Developerayo** [comment]
Please could you add a little commit description? @MAPESO

**Comment by markozxuu** [comment]
of course ! @Developerayo  :)

**Comment by Developerayo** [comment]
Thanks 🔥 @MAPESO

**Pull request merged**
